language: node_js

node_js:
  - '6'

env:
  - WEBPACK_VERSION=V4
  - WEBPACK_VERSION=V3

before_install:
  - if [ "$WEBPACK_VERSION" = "V3" ]; then  rm -f package-lock.json; cp -f ./package.webpack3.json ./package.json; fi

cache:
  directories:
    - node_modules

sudo: false

after_success:
- npm run coveralls
